name: Release

on:
  push:
    tags:
      - 'v*'

jobs:  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run Unit Tests
        run: |
          go install .
          go test -v .
          cd ./examples/simple && go run .
          cd ../complex && go run .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Latest Release for terraform-resources:
            NOTES:

            ENHANCEMENTS:

            INTERNALS:
          draft: false
          prerelease: false
  
  package:
    name: Update Golang package
    runs-on: ubuntu-latest
    needs: release
    steps:  
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          check-latest: true
      - name: Pull latest version from proxy
        run: |
          echo -e "package main\n\nfunc main(){}" > main.go
          go mod init junk
          go mod tidy
          GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/S7R4nG3/terraform-resources@${{ github.ref_name }}