name: Release

on:
  push:
    tags:
      - 'v*'

jobs:  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: Run Unit Tests
        run: |
          GOPROXY=https://proxy.golang.org GO111MODULE=on go install github.com/S7R4nG3/terraform-resources@${{ github.ref }}
          go test -v .
          cd ./examples/simple && go run .
          cd ../complex && go run .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Latest Release for terraform-resources:
            NOTES:

            ENHANCEMENTS:

            INTERNALS:
          draft: false
          prerelease: false