name: Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: unit tests
        run: |
          go install .
          go test -v .

      - name: example builds
        run: | 
          GOPROXY=https://proxy.golang.org GO111MODULE=on go install github.com/S7R4nG3/terraform-resources@${{ github.ref }}
          cd ./examples/simple && go run .
          cd ../complex && go run .